### ISSUE TITLE
Did you get a same result?

### ISSUE THREAD

**Issue by sunwoo76** [bloc97/CrossAttentionControl#13]
Hello.

I have another question.

From your code, I tried to reproduce the results in the prompt-to-prompt.

However, I got a result as below:
![question](https://user-images.githubusercontent.com/38250239/190029306-c0d9517f-0474-4287-b6c2-adc9f9568012.png)

Did you get an identical result? 

How do I set the parameters to get the results in the prompt-to-prompt paper?

And,

Please let me know why you divided latent with "0.1825 before inserting it to VAE.

Thanks :) !!

**Comment by bloc97** [comment]
Something went wrong, I think it's a bug, here's what I got. (On the left both parameters set to 0 and on the right both set to 1)
![image](https://user-images.githubusercontent.com/567732/190153473-1488f9fe-7457-4cfc-ae47-94346209c45d.png)

And for dividing the latent, it's a requirement of the k-lms scheduler used. If you use DDIM you won't need it.
