### ISSUE TITLE
The differences from the official implementation?

### ISSUE THREAD

**Issue by cliangyu** [bloc97/CrossAttentionControl#24]
Hi developers, thank you for completing this wonderful re-implementation.
As I am checking the differences between this repo and the original one, I noticed that the original repo also implemented stable diffusion.

I am wondering if you would like to list the additional features, those exclusive in this repo, on the README page. Will appreciate your clarification very much!

**Comment by bloc97** [comment]
Hi, this implementation was done before the authors had released the code, so in a sense, the official repo's code is more "correct" with respect to the paper, while here I had to take some guesses and add a few modifications.

Currently there are three main differences:
- As there is zero code overlap between the two repos, the license and code ownership is different, (this one is licensed under MIT, official one is Apache)
- The official repo has implemented local editing (using the cross attention masks), while this one does not. [Figure 12, page 12 in the paper]
- This repo has implemented image inversion (finding the latent given an image), while the official repo does not (at least not currently). [Figure 10, page 11 in the paper]

While the actual implementation of the cross-attention control/injection might be slightly different, the results are mostly the same, as I tried to be as faithful to the paper but had to modify the algorithms slightly for stable diffusion. I guess the original authors had to do the same thing but in a different way.
