### ISSUE TITLE
Edit to README.md

### ISSUE THREAD

**Issue by morganavr** [bloc97/CrossAttentionControl#3]
> Image prompt: A fantasy landscape with a pine forest without fog and without rocks
> However, we still see fog and rocks.

That's not how SD works.
You can't type a prompt: "not a woman without a crown not wearing a red dress" and expect SD to follow it.
You will 100% get "a woman, a crown, wearing red dress" 

If you want to have a forest without fog and rocks just don't make these words a part of the prompt or specify alternative words.
Like "A fantasy landscape with a pine forest with a shiny morning sun and with asphalt road".

**Comment by bloc97** [comment]
The point is that LLIMs do not respond correctly to prompts, and is what this method alleviates, you can actually write "with rocks" and apply a negative modifier of something like `-8` to remove rocks from the image.

**Comment by morganavr** [comment]
This feature reminds me ["Weighted Prompts" ](https://github.com/lstein/stable-diffusion#weighted-prompts) from lstein repo.
But it seems that Cross Attention Control allows more precise control over changes.

**Comment by bloc97** [comment]
It's very similar, but working with attention maps allows us to attach negative weights, sometimes a very large negative weight and it does not break the image.
